# ===============================
# = Server Cofiguration
# ===============================
server:
  port: 12000
  servlet:
    context-path: /

  # ========================
  # HTTPS
  # ========================
  ssl:
    key-store: classpath:keystore/batchfetch-c2b.p12
    key-store-password: batchfetch-c2b
    keyStoreType: PKCS12
    keyAlias: batchfetch-c2b

# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    username: c2buser
    password: 8Mo5{^m?J/RK
    url: jdbc:mysql://192.168.30.4:3306/batchfetch_c2b?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=EAT

    testWhileIdle: true
    validationQuery: SELECT 1
    initialization-mode: always



  #  ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show_sql: false
    format_sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        enable_lazy_load_no_trans: true






