
# ============================================
# Profiles
# ===========================================
spring:
  profiles:
    active: dev

  # =================================
  # Pagination
  # =================================
  data:
    web:
      pageable:
        default-page-size: 200
